Docs: Add docker-compose.yml example and use binary as entrypoint in readme `docker run` examples
startersclan/docker-sourceservers pull request #23
Opened 2021-09-03 18:33 UTC by leojonathanoh

Adds example documentation, so that newer users know how to run servers using docker.

Related: #1, #3, #22

@joeltimothyoh

2021-09-03 18:35 UTC, leojonathanoh commented
@joeltimothyoh i've tested, these work nicely. And it does not rely on the in-built `ENTRYPOINT [ "bin/bash", "-c" ]` as a convenience feature making `CMD`'s first argument PID-1.

2021-09-22 23:56 UTC, joeltimothyoh requested changes
lgtm. We should add some pointers to entrypoint write-up as well in https://github.com/startersclan/docker-sourceservers/blob/cb9f2ec9fa3c303ed00ab6b6a19ee02324ae74f7/README.md

Also, should we decide on adopt use of entrypoint `*_linux`, we could adopt the same for use in CI environments.

2021-09-25 03:44 UTC, leojonathanoh commented
@joeltimothyoh added docs under `ENTRYPOINT` and `CMD section

2021-09-29 19:48 UTC, leojonathanoh commented on docker-compose.yml
> +  csgo:
lowest version for widest compatibility, important for open source projects. If the keys used in the definition only require `2.2`, then `2.2` might be sufficient.

2021-09-29 19:49 UTC, leojonathanoh commented on README.md
> +docker run -it -p 27016:27016/udp --entrypoint hlds_linux goldsourceservers/cstrike:latest -game cstrike +port 27016 +maxplayers 10 +map de_dust2
yes. If the idea is to use the server binary.

2021-09-29 19:49 UTC, leojonathanoh commented on docker-compose.yml
> +version: '2.2'
lowest version for widest compatibility, important for open source projects. If the keys used in the definition only require 2.2, then 2.2 might be sufficient.

2021-09-29 20:02 UTC, joeltimothyoh commented on docker-compose.yml
> +  csgo:
If not then I don’t see a need for it.

2021-09-29 20:03 UTC, joeltimothyoh commented on README.md
> +docker run -it -p 27016:27016/udp --entrypoint hlds_linux goldsourceservers/cstrike:latest -game cstrike +port 27016 +maxplayers 10 +map de_dust2
Acceptable.

2021-09-29 20:04 UTC, joeltimothyoh commented on docker-compose.yml
> +version: '2.2'
Sounds good.

2021-09-30 17:33 UTC, leojonathanoh commented on docker-compose.yml
> +  csgo:
@joeltimothyoh i added a comment for each of the services: `hlds` and `srcds`

2021-10-02 04:01 UTC, joeltimothyoh commented
I'm thinking I would prefer if PR source branches were from forked repositories. Reason being that this repo is OSS and that all contributors are part of the same comunity. But with said workflow source branches would not be stored within this repository and can be removed from forked repos. Yet with squash commits it doesn't matter since all changes will be condensed into a single commit independent of source branches. Thoughts @leojonathanoh

2021-10-02 07:20 UTC, leojonathanoh commented
> I'm thinking I would prefer if PR source branches were from forked repositories. Reason being that this repo is OSS and that all contributors are part of the same community. But with said workflow source branches would not be stored within this repository and can be removed from forked repos. Yet it wouldn't matter if squash commits are used as all changes within PRs will be condensed into a single commit independent of source branches. Thoughts @leojonathanoh

To me, it really doesn't matter how many branches there are in a git repo. That's how it's meant to be used. It also provides better traceability if branches are kept.

> Also CircleCI never used to offer a way of limiting of CI jobs to certain branches. As such pushes to branches within this repo would trigger creation of pipeline jobs which contaminates CI log histories and CI notification histories. Perhaps there's a way to limit so now. Yet this is another legitimate reason for source branches being from forked repos.

it should be no different whether the PR was initiated by a fork or on the very repo itself. The pipeline created is a PR pipeline.

2021-10-02 08:40 UTC, joeltimothyoh commented
> To me, it really doesn't matter how many branches there are in a git repo. That's how it's meant to be used. It also provides better traceability if branches are kept.

Thing is this repo is designed to be pipeline based rather than branch based and so does not follow the conventional use of branches.

> it should be no different whether the PR was initiated by a fork or on the very repo itself. The pipeline created is a PR pipeline.

It matters though with CircleCI. You would see from the CI job logs and notification histories that only PRs of this pipeline triggered lots of failed jobs from creation of the source branch and subsequent force-pushes, but which isn't the case for PRs where source branches are from forked repositories. @leojonathanoh

2021-10-02 19:19 UTC, leojonathanoh commented
> Thing is this repo is designed to be pipeline based rather than branch based and so does not follow the conventional use of branches.

true. these CI configs really have limitations. At least github workflows can limit pipeline to branch names. If it be, and github runners have more space now, it's just be better to move from all of those CIs.

> It matters though with CircleCI. You would see from the CI job logs and notification histories that only PRs of this pipeline triggered lots of failed jobs from creation of the source branch and subsequent force-pushes, but which isn't the case for PRs where source branches are from forked repositories. @leojonathanoh

yes. it's a problem with circleci's config that does not allow limiting pipelines to certain branch names. it's better to move on if there's a better ci.

2021-10-02 21:13 UTC, joeltimothyoh commented
> true. these CI configs really have limitations. At least github workflows can limit pipeline to branch names. If it be, and github runners have more space now, it's just be better to move from all of those CIs.

Possible to move except for storage space on GHA makes it impossible to build the larger games on it.

2021-10-02 23:14 UTC, leojonathanoh commented
GHA 37GB available. just a little too small https://github.com/theohbrothers/docker-ansible/runs/3612854410?check_suite_focus=true#step:3:72

2021-10-03 05:26 UTC, joeltimothyoh commented
> GHA 37GB available. just a little too small https://github.com/theohbrothers/docker-ansible/runs/3612854410?check_suite_focus=true#step:3:72

Yes, and without log retention. Not an option @leojonathanoh

2021-10-03 13:11 UTC, leojonathanoh commented
let me reopen a PR from my fork

2021-10-03 14:26 UTC, leojonathanoh commented
Closing in favor of #26

2021-10-03 14:26 UTC, closed without merging